:name: Python Calculator Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies (if any)
        run: |
          python -m pip install --upgrade pip
          pip install pytest #if you are using pytest

      - name: Run Python script
        run: python calculator.py # Ensure your main script is named calculator.py

      - name: Run tests (if you have tests)
        run: |
          pytest tests/test_calculator.py # Assuming tests are in a 'tests' folder, and your test file is test_calculator.py.
          #Or
          #python -m unittest discover -s tests #if you are using unittest.
