name: validation
on:
  workflow_dispatch:

jobs:
  test_calculator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run tests
        run: |
          output=$(python calculator.py 2 2 1)
          echo "$output" | grep "The sum of 2 and 2 is 4.0"
          output=$(python calculator.py 5 2 2)
          echo "$output" | grep "The difference of 5 and 2 is 3.0"
          output=$(python calculator.py 3 3 3)
          echo "$output" | grep "The product of 3 and 3 is 9.0"
          output=$(python calculator.py 10 2 4)
          echo "$output" | grep "The quotient of 10 and 2 is 5.0"
